MyCafe/Models/SendEmailViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MyCafe_v1._5.Models
{
    public class SendEmailViewModel
    {       
        [Display(Name = "Email address")]
        [Required(ErrorMessage = "Please enter an email address.")]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string ToEmail { get; set; }

        [Required(ErrorMessage = "Please enter a subject.")]
        public string Subject { get; set; }

        [Required(ErrorMessage = "Please enter the contents")]
        public string Contents { get; set; }

        [Display(Name = "Upload File")]
        public string FilePath { get; set; }
        public HttpPostedFileBase Attachment { get; set; }
    
    }
}

MyCafe/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyCafe_v1._5.Models;

namespace MyCafe_v1._5.Controllers
{
    public class EmployeesController : Controller
    {
        private OrderSystemContainer db = new OrderSystemContainer();

        // GET: Employees
        [Authorize(Roles = "Administrator, Manager, Employee")]
        public ActionResult Index()
        {
            return View(db.Employees.ToList());
        }

        // GET: Employees/Details/5
        [Authorize(Roles = "Administrator, Manager")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // GET: Employees/Create
        [Authorize(Roles = "Administrator, Manager")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Employees/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator, Manager")]
        public ActionResult Create([Bind(Include = "Id,FirstName,LastName,Birthday,RegisterTime")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                db.Employees.Add(employee);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(employee);
        }

        // GET: Employees/Edit/5
        [Authorize(Roles = "Administrator, Manager")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator, Manager")]
        public ActionResult Edit([Bind(Include = "Id,FirstName,LastName,Birthday,RegisterTime")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                db.Entry(employee).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(employee);
        }

        // GET: Employees/Delete/5
        [Authorize(Roles = "Administrator, Manager")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator, Manager")]
        public ActionResult DeleteConfirmed(int id)
        {
            Employee employee = db.Employees.Find(id);
            db.Employees.Remove(employee);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MyCafe/Controllers/HomeController.cs
using MyCafe_v1._5.Models;
using MyCafe_v1._5.Utils;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyCafe_v1._5.Controllers
{
    [RequireHttps]
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "Administrator, Manager, Employee")]
        public ActionResult Main()
        {
            return View();
        }

        [Authorize(Roles = "Administrator, Manager, Employee")]
        public ActionResult Send_Email()
        {
            return View(new SendEmailViewModel());
        }

        [HttpPost]    
        public ActionResult Send_Email(SendEmailViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    String toEmail = model.ToEmail;
                    String subject = model.Subject;
                    String contents = model.Contents;

                    //String path = model.Attachment.ToString();
                    //string fileName = model.Attachment.FileName;

                    String fileName = model.FilePath;
                    string filePath = Server.MapPath("~/"+fileName);

                    EmailSender es = new EmailSender();
                    es.Send(toEmail, subject, contents, filePath, fileName);

                    ViewBag.Result = "Email has been send.";

                    ModelState.Clear();

                    return View(new SendEmailViewModel());
                }
                catch
                {
                    return View();
                }
            }

            return View();
        }    


        [Authorize]
        public ActionResult Map()
        {
            return View();
        }


        [HttpGet]
        [Authorize(Roles = "Administrator, Manager, Employee")]
        public ActionResult UploadFile()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Administrator, Manager, Employee")]
        public ActionResult UploadFile(HttpPostedFileBase file)
        {
            try
            {
                if (file != null)
                {
                    string fileName = Path.GetFileName(file.FileName);

                    string path = Server.MapPath(string.Format("~/{0}", "Uploads"));
                  
                    if (!Directory.Exists(path))
                    {
                        Directory.CreateDirectory(path);
                    }

                    file.SaveAs(Path.Combine(path, fileName));

                    ViewBag.Message = "File uploaded successfully";
                }
                return View();
            }
            catch
            {
                ViewBag.Message = "File uploaded failed";
                return View(new SendEmailViewModel());
            }

        }

    }
}

MyCafe/Controllers/InnovativeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyCafe_v1._5.Controllers
{
    public class InnovativeController : Controller
    {
        // GET: Innovative
        [Authorize(Roles = "Administrator, Manager, Employee")]
        public ActionResult Index()
        {
            return View();
        }

    }
}

MyCafe/Controllers/MenusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyCafe_v1._5.Models;

namespace MyCafe_v1._5.Controllers
{
    public class MenusController : Controller
    {
        private OrderSystemContainer db = new OrderSystemContainer();

        // GET: Menus
        [Authorize(Roles = "Administrator, Manager, Employee")]
        public ActionResult Index()
        {
            var menus = db.Menus.Include(m => m.Employee);
            return View(menus.ToList());
        }

        // GET: Menus/Details/5
        [Authorize(Roles = "Administrator, Manager, Employee")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Menu menu = db.Menus.Find(id);
            if (menu == null)
            {
                return HttpNotFound();
            }
            return View(menu);
        }

        // GET: Menus/Create
        [Authorize(Roles = "Administrator, Manager")]
        public ActionResult Create()
        {
            ViewBag.EmployeeId = new SelectList(db.Employees, "Id", "FirstName");
            return View();
        }

        // POST: Menus/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator, Manager")]
        public ActionResult Create([Bind(Include = "Id,Name,Price,Description,EmployeeId,MCreateTime")] Menu menu)
        {
            if (ModelState.IsValid)
            {
                db.Menus.Add(menu);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.EmployeeId = new SelectList(db.Employees, "Id", "FirstName", menu.EmployeeId);
            return View(menu);
        }

        // GET: Menus/Edit/5
        [Authorize(Roles = "Administrator, Manager")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Menu menu = db.Menus.Find(id);
            if (menu == null)
            {
                return HttpNotFound();
            }
            ViewBag.EmployeeId = new SelectList(db.Employees, "Id", "FirstName", menu.EmployeeId);
            return View(menu);
        }

        // POST: Menus/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator, Manager")]
        public ActionResult Edit([Bind(Include = "Id,Name,Price,Description,EmployeeId,MCreateTime")] Menu menu)
        {
            if (ModelState.IsValid)
            {
                db.Entry(menu).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.EmployeeId = new SelectList(db.Employees, "Id", "FirstName", menu.EmployeeId);
            return View(menu);
        }

        // GET: Menus/Delete/5
        [Authorize(Roles = "Administrator, Manager")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Menu menu = db.Menus.Find(id);
            if (menu == null)
            {
                return HttpNotFound();
            }
            return View(menu);
        }

        // POST: Menus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator, Manager")]
        public ActionResult DeleteConfirmed(int id)
        {
            Menu menu = db.Menus.Find(id);
            db.Menus.Remove(menu);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MyCafe/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyCafe_v1._5.Models;

namespace MyCafe_v1._5.Controllers
{
    [Authorize(Roles = "Administrator, Manager, Employee")]
    public class OrdersController : Controller
    {
        private OrderSystemContainer db = new OrderSystemContainer();

        // GET: Orders
        public ActionResult Index()
        {
            var orders = db.Orders.Include(o => o.Employee);
            return View(orders.ToList());
        }

        // GET: Orders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // GET: Orders/Create
        public ActionResult Create()
        {
            ViewBag.EmployeeId = new SelectList(db.Employees, "Id", "FirstName");
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,EmployeeId,CreateTime,ProcessTime")] Order order)
        {
            if (ModelState.IsValid)
            {
                db.Orders.Add(order);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.EmployeeId = new SelectList(db.Employees, "Id", "FirstName", order.EmployeeId);
            return View(order);
        }

        // GET: Orders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            ViewBag.EmployeeId = new SelectList(db.Employees, "Id", "FirstName", order.EmployeeId);
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,EmployeeId,CreateTime,ProcessTime")] Order order)
        {
            if (ModelState.IsValid)
            {
                db.Entry(order).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.EmployeeId = new SelectList(db.Employees, "Id", "FirstName", order.EmployeeId);
            return View(order);
        }

        // GET: Orders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Order order = db.Orders.Find(id);
            db.Orders.Remove(order);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MyCafe/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<link href="~/Content/Carousel/bootstrap.min.css" rel="stylesheet" />
<link href="~/Content/footer-distributed-with-address-and-phones.css" rel="stylesheet" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
<script src="~/Scripts/Carousel/jquery.min.js"></script>
<script src="~/Scripts/Carousel/popper.min.js"></script>
<script src="~/Scripts/Carousel/bootstrap.min.js"></script>
<style>
    /* Make the image fully responsive */
    .carousel-inner img {
        width: 100%;
        height: 60%;
    }

    .homelogo {
        color: white;
        font-size: 30px;
    }

    .lognv {
        color: white;
        font-size: 20px;
    }

    
</style>


<nav class="navbar navbar-expand-md navbar-dark bg-dark sticky-top">
    <div class="container-fluid">
        @Html.ActionLink("My Cafe", "Index", "Home", new { area = "" }, new { @class = "navbar-brand homelogo" })

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mynav">
            <span class="navbar-toggler-icon"></span>
        </button>


        <div class="collapse navbar-collapse" id="mynav">
            <ul class="navbar-nav ml-auto lognv">
                @if (Request.IsAuthenticated)
                {
                    @Html.AntiForgeryToken()
                <li>
                    @Html.ActionLink("My Page", "Main", "Home")
                    <a>  &nbsp &nbsp </a>
                </li>               
                    

                    using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                    {
                        @Html.AntiForgeryToken()

                        <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
                    }

                }
                else
                {

                    <li>@Html.ActionLink("Log in", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink", @class = "lognv" })</li>

                }

            </ul>
        </div>
    </div>
</nav>




<section>
    <div id="slides" class="carousel slide" data-ride="carousel">
        <ul class="carousel-indicators">
            <li data-target="#slides" data-slide-to="0" class="active"></li>
            <li data-target="#slides" data-slide-to="1"></li>
            <li data-target="#slides" data-slide-to="2"></li>
        </ul>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="~/Assets/Images/cafe-266651_1280.jpg" />
                <div class="carousel-caption">
                    <h1>Welcome to My Cafe</h1>
                </div>
            </div>
            <div class="carousel-item">
                <img src="~/Assets/Images/coffee-358859_1280.jpg" />
                <div class="carousel-caption">
                    <h1>Welcome to My Cafe</h1>
                </div>
            </div>
            <div class="carousel-item">
                <img src="~/Assets/Images/Restaurant-Popota.jpg" />
                <div class="carousel-caption">
                    <h1>Welcome to My Cafe</h1>
                </div>
            </div>
        </div>

    </div>
</section>


<footer class="footer-distributed">

    <div class="footer-left">
        <h1 style="font-size:4vw;">Opening Hour</h1>
        <p style="font-size:2vw;">Weekday: 10:00 - 20: 00 </p>
        <br>
        <p style="font-size:2vw;">Weekend: 10:00 - 22: 00 </p>

    </div>

    <div class="footer-center">
        <h1 style="font-size:4vw;">Contact</h1>
        <p style="font-size:2vw;">Phone Number: 0-000-000-000</p>
        <p style="font-size:2vw;">Email: email@email.com</p>
        <h1 style="font-size:4vw;">Address</h1>
        <p style="font-size:2vw;">Monash Caufield Campus</p>
        <a href="@Url.Action("Map", "Home")"><i class="fa fa-map-marker"></i></a>


    </div>

    <div class="footer-right">

        <h1 style="font-size:4vw;">Follow us</h1>

        <div class="footer-icons" style="font-size:2vw;">

            <a href="#"><i class="fa fa-facebook"></i></a>
            <a href="#"><i class="fa fa-twitter"></i></a>
            <a href="#"><i class="fa fa-linkedin"></i></a>
            <a href="#"><i class="fa fa-github"></i></a>
           
        </div>
        <br>

        <div class="content" id='map'></div>

    </div>

    

</footer>

MyCafe/Views/Home/Main.cshtml
@model MyCafe_v1._5.Models.Employee

@{
    ViewBag.Title = "Main";
    Layout = "~/Views/Shared/Operation.cshtml";
}


    <div class="content-wrapper">
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="card">
                            <div class="card-header">
                                <h5 class="m-0">Account Management</h5>
                            </div>
                            <div class="card-body">
                                <h6 class="card-title">Create/ Edit/ Delete/ the accounts</h6>
                                <br>
                                <a href="#" class="btn btn-primary">Go somewhere</a>
                            </div>
                        </div>

                        <div class="card card-primary card-outline">
                            <div class="card-header">
                                <h5 class="m-0">Employee Management</h5>
                            </div>
                            <div class="card-body">
                                <h6 class="card-title">Create/ Edit/ Delete/ the employee profiles</h6>
                                <br>
                                @Html.ActionLink("All Employees", "Index", "Employees", new { area = "" }, new { @class = "btn btn-primary" })
                            </div>
                        </div>

                        <div class="card card-primary card-outline">
                            <div class="card-header">
                                <h5 class="m-0">Live Chat</h5>
                            </div>
                            <div class="card-body">
                                <h6 class="card-title">Chat with online colleagues</h6>
                                <br>
                                @Html.ActionLink("Join", "Index", "Innovative", new { area = "" }, new { @class = "btn btn-primary" })
                            </div>
                        </div>

                    </div>
                    <!-- /.col-md-6 -->
                    <div class="col-lg-6">
                        <div class="card">
                            <div class="card-header">
                                <h5 class="m-0">Menu Management</h5>
                            </div>
                            <div class="card-body">
                                <h6 class="card-title">Create/ Edit/ Delete/ the menu</h6>
                                <br>
                                @Html.ActionLink("View Menus", "Index", "Menus", new { area = "" }, new { @class = "btn btn-primary" })
                            </div>
                        </div>

                        <div class="card card-primary card-outline">
                            <div class="card-header">
                                <h5 class="m-0">Order Management</h5>
                            </div>
                            <div class="card-body">
                                <h6 class="card-title">Create/ Edit/ Delete/ the orders</h6>
                                <br>
                                @Html.ActionLink("View Orders", "Index", "Orders", new { area = "" }, new { @class = "btn btn-primary" })
                            </div>
                        </div>

                        <div class="card card-primary card-outline">
                            <div class="card-header">
                                <h5 class="m-0">Email Services</h5>
                            </div>
                            <div class="card-body">
                                <h6 class="card-title">Send email to customers</h6>
                                <br>
                                @Html.ActionLink("Send Email", "Send_Email", "Home", new { area = "" }, new { @class = "btn btn-primary" })
                            </div>
                        </div>
                    </div>
                    <!-- /.col-md-6 -->
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content -->
    </div>

MyCafe/Views/Home/Send_Email.cshtml
@model MyCafe_v1._5.Models.SendEmailViewModel

@{
    ViewBag.Title = "Send_Email";
    ViewBag.Message = "";
    Layout = "~/Views/Shared/Operation.cshtml";
}


<div class="content-wrapper">
<h2>Send_Email</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


    if (@ViewBag.Result != null)
    {
        <div class="alert alert-info">@ViewBag.Result</div>
    }   

<div class="form-horizontal">
    <h4>SendEmailViewModel</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.ToEmail, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ToEmail, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ToEmail, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Contents, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Contents, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Contents, "", new { @class = "text-danger" })
        </div>
    </div>    

   <form action='@Url.Action("UploadFile", "Home")' method="post" enctype="multipart/form-data" class="control-label col-md-2">  
        <input type="file" value="Add an attachment" formaction="@Url.Action("UploadFile", "Home")"/>
    </form>




    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Send" class="btn btn-default"/>
        </div>
    </div>
</div>


    }

    <div>
        @Html.ActionLink("Back to Home", "Main")
    </div>

    </div>
@section Scripts {

    <script src="~/Scripts/respond.min.js"></script>
}

MyCafe/Views/Home/UploadFile.cshtml
@{
    ViewBag.Title = "UploadFile";
    Layout = "~/Views/Shared/Operation.cshtml";
}

<div class="content-wrapper">
    <h2>UploadFile</h2>

    <form action='@Url.Action("UploadFile", "Home")' method="post" enctype="multipart/form-data">
        <input type="file" name="file" value="FilePath"/>
        <input type="submit" value="add an attachment" />
        @Html.ActionLink("Back to Email", "Send_Email", "Home", new { area = "" }, new { @class = "btn btn-primary" })
    </form>
    @ViewBag.Message

</div>